[tool.poetry]
name = "deepeval"
version = "2.0.5"
description = "The Evaluation Framework for LLMs"
authors = ["Jeffrey Ip <jeffreyip@confident-ai.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/confident-ai/deepeval"
documentation = "https://docs.confident-ai.com"

[tool.poetry.scripts]
deepeval = 'deepeval.cli.main:app'

[tool.poetry.plugins."pytest11"]
plugins = "deepeval.plugins.plugin"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
requests = "*"
tqdm = "*"
pydantic = "*"
pytest = "*"
pytest-xdist = "*"
pytest-repeat = "*"
pytest-rerunfailures = "^12.0"
pytest-asyncio = "^0.21.1"
tabulate = "*"
sentry-sdk = "*"
rich = "*"
coverage = "*"
portalocker = "*"
openai = "*"
langchain = "*"
langchain-core = "*"
langchain_openai = "*"
langchain_community = "*"
protobuf = "*"
typer = "*"
setuptools = "*"
wheel = "*"
aiohttp = "*"
llama-index = "*"
llama-index-llms-langchain = "*"
docx2txt = "^0.8"
importlib-metadata = ">=6.0.2"
tenacity = "^8.4.1"
opentelemetry-api = "^1.24.0"  
opentelemetry-sdk = "^1.24.0" 
opentelemetry-exporter-otlp-proto-grpc = "^1.24.0" 
grpcio = "1.60.1"
instructor = "*"
twine="5.1.1"
nest-asyncio = "*"

[tool.poetry.group.dev.dependencies]
black = "*"

[tool.black]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-m 'not skip_test'"
markers = [
    "skip_test: skip the test",
]
